import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

// Font files can be colocated inside of `app`
const orkney = localFont({
  variable: '--font-orkney',
  display: 'swap',
  src: [
    {
      path: './../assets/fonts/orkney/orkney-regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../assets/fonts/orkney/orkney-regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orkney.className} ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
